language: python
python: "2.7.13"

branches:
  - master

os:
  - linux

#env variables
env:
  global:
  - CODECOV_TOKEN="c78a5d49-2eb3-4844-ab1c-a009e9162f4e"

# command to install dependencies
install:
  - pip install .
  - pip install coverage
  - pip install codecov

before_script:
  - LOC=/home/travis/virtualenv/python2.7.13  # Location where VE is created on travis
  - sed -i 's|VENV|'"$LOC"'|g' .coveragerc  # Update source in coveragerc
  - cat .coveragerc

script:
  - coverage run -m pytest -vvv tests/test_api/
  - coverage run -m pytest -vvv tests/test_components/
  - coverage run -m pytest -vvv tests/test_entities/

after_success:
  - coverage combine
  - coverage xml
  - codecov
  - curl -s https://codecov.io/bash | bash

# services:
# - rabbitmq